Added:Control Certer Backend APIs
beckn/beckn-action-bot pull request #45
Opened 2024-03-29 14:31 UTC by shreyvishal

## Description
Added:Control Certer Backend APIs

## Features covered
[Create a control center](https://github.com/beckn/beckn-action-bot/issues/29)

## Changes made
Added APIs for Control Center UI

## Screenshots/recordings
NA

## Testing
NA

## Self checks

- [ ] Code follows coding style guidelines.
- [ ] All tests pass successfully.
- [ ] No new linting errors or warnings.
- [ ] Documentation is updated, if necessary.
- [ ] Dependencies are updated, if required.
- [ ] There are no merge conflicts.

## Reviewer Suggestions
NA

2024-03-31 14:51 UTC, mayurvir requested changes
There are a lot of things not right with this PR. 

Also, the code never worked, it failed existing test cases and are missing environment variables. Please fix and add additional test cases for the changes.

2024-03-31 14:51 UTC, mayurvir commented on controllers/ControlCenter.js
> +        const getOrderFulfillmentDetails = await axios.get(
We could re-use the `call_api` function instead of all axios calls.

2024-03-31 14:51 UTC, mayurvir commented on controllers/ControlCenter.js
> +const TOURISM_STRAPI_URL = process.env.TOURISM_STRAPI_URL || ''
New environment variables need to be added to the .env.sample file

2024-03-31 14:51 UTC, mayurvir commented on server.js
> +import { notificationController } from './controllers/Notification.js'
Can't find this controller.

2024-03-31 14:51 UTC, mayurvir commented on controllers/ControlCenter.js
> +            await action.send_message(TWILIO_RECEPIENT_NUMBER, messageBody)
Why are we using twilio recipient number, shouldn't this be the user's number?

2024-03-31 14:51 UTC, mayurvir commented on controllers/ControlCenter.js
> +export const notificationController = async (req, res) => {
Not sure we we can put one controller inside another. Why can't we use a function for this?

2024-03-31 14:51 UTC, mayurvir commented on services/notificationService.js
> +export const sendWhatsappNotification = async (
Can't we use the `send_message()` from Actions.js service here?

2024-03-31 14:51 UTC, mayurvir commented on utils/constants.js
> +export const STRAPI_TOURISM_TOKEN =
lets keep this under the config folder. Its not a utility. As a practise, things that are not keys etc. should be kept here so Token should be an environment variable whereas `TOURISM_STRAPI_URL` should be under config .

2024-04-01 04:56 UTC, shreyvishal commented on controllers/ControlCenter.js
> +        const getOrderFulfillmentDetails = await axios.get(
This is done

2024-04-01 04:59 UTC, shreyvishal commented on controllers/ControlCenter.js
> +const TOURISM_STRAPI_URL = process.env.TOURISM_STRAPI_URL || ''
Done

2024-04-01 04:59 UTC, shreyvishal commented on server.js
> +import { notificationController } from './controllers/Notification.js'
Done

2024-04-01 05:00 UTC, shreyvishal commented on controllers/ControlCenter.js
> +            await action.send_message(TWILIO_RECEPIENT_NUMBER, messageBody)
From where should the user's number be provided, from the payload sent by the FE?? @mayurvir

2024-04-01 05:06 UTC, shreyvishal commented on controllers/ControlCenter.js
> +export const notificationController = async (req, res) => {
Need Clarity for this @mayurvir

2024-04-01 05:21 UTC, shreyvishal commented on utils/constants.js
> +export const STRAPI_TOURISM_TOKEN =
Done

2024-04-02 07:43 UTC, mayurvir requested changes

2024-04-02 07:43 UTC, mayurvir commented on config/openai.json
> -        { "role": "system", "content": "For `select`, `init`, `confirm`, you must use the item `id` as part of the payload for selected item instead of name or any other key."}
Why is the prompt changed for line #14?

2024-04-02 07:43 UTC, mayurvir commented on config/openai.json
> +        "bap_uri": "https://mit-ps-bap.becknprotocol.io",
This should not be here under openai.json. 

One that things like bap_id, bap_uri etc are now part of registry.json
Strapi url is not openai related config, it should be under a different file like `config.json` or constants.js file that you have created.

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +const STRAPI_TOURISM_TOKEN = process.env.STRAPI_TOURISM_TOKEN || ''
No need to re-decalre `STRAPI_TOURISM_TOKEN ` or `STRAPI_TOURISM_TOKEN ` as they can be used directly from the environment variables.

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +            return res.status(500).json({message:"Order Id is Required", status:false})
500 is for internal server error, you should use 400 for a bad request , typically used for missing data.

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +            return res.send({ message: `Invalid Order Id`, status:false })
Status should be 400, its sending 200 when the order id is invalid. Isn't it a bad request?

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +        return res.send({ message: 'Cancel Booking Failed' })
status code should not be 200.

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +        return res.send({ message: error.message })
status should not be 200.

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +        return res.send({ message: error.message })
Status code should not be 200.

2024-04-02 07:43 UTC, mayurvir commented on controllers/ControlCenter.js
> +        return res.send({ message: error.message })
Status code should not be 200.

2024-04-02 07:43 UTC, mayurvir commented on services/Actions.js
> +            // logger.info(JSON.stringify(response.data, null, 2))
Remove the comment, unnecessary change.

2024-04-02 07:43 UTC, mayurvir commented on tests/unit/controllers/controlCenter.test.js
> +            "userNo":"+919123456789"
This looks like a valid number, it should be something like "INVALID_NUMBER", a string is invalid number and it will defiitely faill. Test cases should be written in such a way that they always do what they are supposed to do. They should not be flaky (which works sometimes and dont work sometimes)

2024-04-02 07:43 UTC, mayurvir commented on tests/unit/controllers/controlCenter.test.js
> +        expect(response._body.status.status).to.not.equal('failed')
If its succes case, why are we testing for failure?

2024-04-02 07:43 UTC, mayurvir commented on tests/unit/controllers/controlCenter.test.js
> +        expect(response._body.status.status).to.not.equal('failed')
If its a sucess, response, why is the status being test against `failed`?

2024-04-02 07:43 UTC, mayurvir commented on tests/unit/controllers/controlCenter.test.js
> +        expect(response._body.message).equal('Notification delivered')
Should check for status also.

2024-04-02 07:43 UTC, mayurvir commented on tests/unit/controllers/controlCenter.test.js
> +describe('API tests for /update-catalog endpoint for an end to end Notify Message', () => {
Should check for status codes and status flags as well, testing against response message is not enough.

2024-04-03 15:33 UTC, mayurvir requested changes
BIggest problem is with unit tests not running fully.

2024-04-03 15:33 UTC, mayurvir commented on config/openai.json
> -        { "role": "system", "content": "For `select`, `init`, `confirm`, you must use the item `id` as part of the payload for selected item instead of name or any other key."}
This needs to be fixed.

2024-04-03 15:33 UTC, mayurvir commented on tests/unit/services/actions.test.js
> +describe.only('should test send_message()', () => {
Why `only`?

2024-04-03 15:33 UTC, mayurvir commented on tests/unit/services/actions.test.js
> -
`Nitpick`, Unnecessary line break.

2024-04-03 15:40 UTC, shreyvishal commented on tests/unit/services/actions.test.js
> -
Done

2024-04-03 15:40 UTC, shreyvishal commented on tests/unit/services/actions.test.js
> +describe.only('should test send_message()', () => {
done

2024-04-03 17:37 UTC, mayurvir approved these changes

2024-04-03 17:37 UTC, merged